version: '3.9'

services:
  generator-service-1:
    build:
      context: ./generator-service
      dockerfile: Dockerfile
    container_name: generator-service-1
    hostname: generator-service-1
    ports:
      - "5000:5000"
    environment:
      - APP_NAME=Service generator 1
      - PORT=5000
    networks:
      - main

  generator-service-2:
    build:
      context: ./generator-service
      dockerfile: Dockerfile
    container_name: generator-service-2
    hostname: generator-service-2
    ports:
      - "5001:5001"
    environment:
      - APP_NAME=Service generator 2
      - PORT=5001
    networks:
      - main

  generator-service-3:
    build:
      context: ./generator-service
      dockerfile: Dockerfile
    container_name: generator-service-3
    hostname: generator-service-3
    ports:
      - "5002:5002"
    environment:
      - APP_NAME=Service generator 3
      - PORT=5002
    networks:
      - main

  load-balancer:
    image: nginx:latest
    container_name: load-balancer
    ports:
      - "8080:80"
    volumes:
      - ./nginx-loadbalancer/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-loadbalancer/config/conf.d:/etc/nginx/conf.d
      - ./nginx-loadbalancer/www:/etc/nginx/home/loadbalancer/www
    networks:
      - main

networks:
  main:
